{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"call_center_transformed\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "b767efe1-5f77-4611-91ad-314039d4f8d4",
        "fromColumn": "date",
        "fromTable": "call_center_transformed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_cbb0b600-5fda-4ac0-9685-88d61d2f64e4"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "call_center_transformed",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70c8de1a-c7e9-46a4-9029-b61639306d24",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          },
          {
            "name": "Incoming Calls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad70e326-d83f-4512-b7e9-46b5c1509dd6",
            "sourceColumn": "Incoming Calls",
            "summarizeBy": "sum"
          },
          {
            "name": "Answered Calls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a71a4ce6-6cfb-489a-aab2-8749750d8b53",
            "sourceColumn": "Answered Calls",
            "summarizeBy": "sum"
          },
          {
            "name": "Answer Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2a89c0ac-3f25-4189-a745-226e18f19d5e",
            "sourceColumn": "Answer Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Abandoned Calls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e618b7b-4fbf-436e-b2cc-369af352b9aa",
            "sourceColumn": "Abandoned Calls",
            "summarizeBy": "sum"
          },
          {
            "name": "Answer Speed (AVG)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "971de8d9-4c10-461d-919a-a1fed87f7b21",
            "sourceColumn": "Answer Speed (AVG)",
            "summarizeBy": "none"
          },
          {
            "name": "Talk Duration (AVG)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "dd658d6d-e044-4808-9a51-4014c1666fc6",
            "sourceColumn": "Talk Duration (AVG)",
            "summarizeBy": "none"
          },
          {
            "name": "Waiting Time (AVG)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "b8549f6d-7e9c-4f5f-aaf8-9ac6b41a6956",
            "sourceColumn": "Waiting Time (AVG)",
            "summarizeBy": "none"
          },
          {
            "name": "Service Level (20 Seconds)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "438dbc8b-faad-4b45-a7df-01cb58c3e20f",
            "sourceColumn": "Service Level (20 Seconds)",
            "summarizeBy": "sum"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ef36424e-0000-49cb-83d8-dde01ee3346a",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_cbb0b600-5fda-4ac0-9685-88d61d2f64e4"
                },
                "isDefault": true,
                "relationship": "b767efe1-5f77-4611-91ad-314039d4f8d4"
              }
            ]
          },
          {
            "name": "avg_ht_sec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e095fcd-7f10-4663-a0ed-27367b23ab54",
            "sourceColumn": "avg_ht_sec",
            "summarizeBy": "sum"
          },
          {
            "name": "avg_wt_sec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "02c079f0-fdc0-46be-9680-d12a45e6fe89",
            "sourceColumn": "avg_wt_sec",
            "summarizeBy": "sum"
          },
          {
            "name": "avg_as_sec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6c82d44e-6a41-4bc2-91ad-1f653716db91",
            "sourceColumn": "avg_as_sec",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d256d66f-bdc5-40f9-9771-f383b6e1559e",
        "partitions": [
          {
            "name": "call_center_transformed",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\josez\\OneDrive\\Documents\\repos\\DataAnalysisPortfolio\\Project 3 - Call Center Analysis\\call_center_transformed.csv\"),[Delimiter=\",\", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"\", Int64.Type}, {\"Index\", Int64.Type}, {\"Incoming Calls\", Int64.Type}, {\"Answered Calls\", Int64.Type}, {\"Answer Rate\", Percentage.Type}, {\"Abandoned Calls\", Int64.Type}, {\"Answer Speed (AVG)\", type time}, {\"Talk Duration (AVG)\", type time}, {\"Waiting Time (AVG)\", type time}, {\"Service Level (20 Seconds)\", Percentage.Type}, {\"date\", type date}, {\"avg_ht_sec\", Int64.Type}, {\"avg_wt_sec\", Int64.Type}, {\"avg_as_sec\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_9c0821be-1616-4d95-939b-e34895a03899",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cfcb3647-c2f0-42aa-b077-a6ff9e25a4de",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b513fc12-3ffd-4f12-8043-d47393ebef32",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6d358541-2333-4c1a-ba39-1827db22f4fd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8b1bac9d-fa6d-41ca-92ad-96f9a0d68911",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "03c6b082-ee0b-41b3-a8a5-243bceab344e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b7ed1883-272c-400c-a0e7-c3fb77069923",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b221b96d-6193-4430-931f-7fdc8faf776f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0d8ad686-0fb4-410a-b1ee-4b8e78043e2e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "51419fb5-266a-42d7-90eb-7f8ff0a172aa",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b4bfc10e-9b23-439a-b033-0116cb3fee59",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "613586ab-f01b-4e51-903c-c1fb0874a31a",
                "ordinal": 3
              }
            ],
            "lineageTag": "e3f32356-d933-427e-9a75-4b76184f0533"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a91b1bff-47de-46d6-9768-9c0b4a3964e7",
        "partitions": [
          {
            "name": "DateTableTemplate_9c0821be-1616-4d95-939b-e34895a03899",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_cbb0b600-5fda-4ac0-9685-88d61d2f64e4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "664d817b-0a28-4f76-9f43-c78b1ca68b88",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4a0f9059-20a5-4531-84b6-776437df3d57",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c6e73944-1aa2-47cd-9bdf-19fd62cfd4fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "560f64c3-cb15-4ff0-872c-deeafbccf9cc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "647c1ebe-1f63-4704-9e2b-ec6eef9947d9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1a5df3b6-a14b-4fd5-9b9b-ccd746900baa",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bd6931b1-12be-461c-9b63-c34ba934c87b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1d4d191e-315e-48aa-a3a2-c04843eaedb8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "bdb92126-9bce-4673-979f-998913caccbf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e631fc36-6d03-4e75-8f3a-769d69e2cbdb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2d529b87-9e3e-4961-a5cf-2ff4d6496420",
                "ordinal": 3
              }
            ],
            "lineageTag": "2e978b1c-feb5-44bd-bbf8-e0d69241d24c"
          }
        ],
        "isHidden": true,
        "lineageTag": "eb8a5d4b-2ea3-43f6-ba66-aa0e7326907a",
        "partitions": [
          {
            "name": "LocalDateTable_cbb0b600-5fda-4ac0-9685-88d61d2f64e4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('call_center_transformed'[date])), 1, 1), Date(Year(MAX('call_center_transformed'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}